"""Write ``meta/excluded_episodes.json`` for a DROID bucket: episodes with no
resolvable prompt.

Why this is REQUIRED, not an optimization
-----------------------------------------
``OxeDroidDataset._resolve_prompt`` raises when ``tasks.parquet`` and every
entry of the fallback chain are blank for a window. The base reader's
``_safe_get`` catches that and retries at ``idx + 1`` up to
``_GETITEM_MAX_RETRIES`` (64) times — but windows are ordered by episode with
``window_stride=1``, so ``idx + 1`` is the *next frame of the same episode*. An
episode with no prompt has no prompt on ANY of its rows (measured: the condition
is all-or-nothing per episode), so the 64-step walk only escapes episodes
shorter than 65 frames. On the 2026-08 bucket, 336 of the 426 affected episodes
are longer than that, the ValueError propagates, and the DataLoader **worker
dies** — which is the documented path to a DDP deadlock (rank 0 hits an early
iterator EOF while its peers are still in a backward NCCL allreduce; see
``test_wrist_decode_failure_is_tolerated``).

Empirically: those episodes are 157,836 of 46,259,014 windows (0.341%), so a
shuffled run kills a worker roughly every ~293 samples. A 16-worker,
batch-size-24 loader died at sample 264.

Dropping them at construction costs 0.28% of episodes and makes the raise in
``_resolve_prompt`` a genuine backstop instead of a live failure mode.

The scan aborts without writing if it finds a partially resolvable episode or a
``task_index`` absent from ``tasks.parquet`` because either condition violates
the reader assumptions above. Existing exclusions and prompt-owned exclusions
are tracked separately, then the canonical list is rebuilt as their union. This
preserves an independently bad episode even when the prompt scan also owns that
same ID. The exact original generator schema is migrated; an ambiguous
namespaced artifact without the ownership ledger is refused rather than guessed
at. Unrelated top-level metadata is preserved. The scan certificate binds the
result to ``tasks.parquet``, the effective ``info.json[data_path]`` template,
the complete episodes manifest path/range mapping, and every prompt-bearing row
inside those addressed ranges. Orphan parquet files and unaddressed tail rows
are not part of the reader population. The reader independently recomputes that
digest before accepting the exclusions.

Usage
-----
    python scripts/write_droid_prompt_exclusions.py \
        --dataset-dir /mnt/data/wangyuran/pretrain_dataset/Droid

    # inspect without writing
    python scripts/write_droid_prompt_exclusions.py --dataset-dir ... --dry-run

Re-run after any change to ``OxeDroidDataset.PROMPT_FALLBACK_COLS`` /
``_PLACEHOLDER_RE``, source data, ``info.json[data_path]``, or the complete
episodes manifest. The scan applies the reader's own ``_clean_text`` and chain
order to every manifest-addressed row, so the two can't drift.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import logging
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

from openwam.dataloader.oxe_droid import (
    DROID_PROMPT_EXCLUSION_KEY,
    DROID_PROMPT_EXCLUSION_SCHEMA_VERSION,
    DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY,
    DROID_PROMPT_INPUTS_DIGEST_KEY,
    OxeDroidDataset,
    _clean_text,
    _sha256_file,
    compute_droid_prompt_inputs_digest,
    digest_droid_prompt_shard,
    read_droid_prompt_population_shard,
)
from openwam.dataloader.utils.exclusion_io import atomic_publish_text, locked_exclusion_files
from openwam.dataloader.utils.lerobotv3 import (
    LeRobotV3DataShard,
    resolve_lerobot_v3_data_population,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

FALLBACK_COLS = list(OxeDroidDataset.PROMPT_FALLBACK_COLS)
PROMPT_REASON = (
    "episodes whose prompt cannot be resolved from tasks.parquet or any "
    "PROMPT_FALLBACK_COLS entry on any row; generated by "
    "scripts/write_droid_prompt_exclusions.py"
)
_TASK_TEXT: dict[int, str] | None = None
_DATASET_DIR: Path | None = None


def _init(dataset_dir: str, task_text: dict[int, str]) -> None:
    global _TASK_TEXT, _DATASET_DIR
    _DATASET_DIR = Path(dataset_dir)
    _TASK_TEXT = task_text


def _scan_shard(shard: LeRobotV3DataShard) -> dict:
    """Resolve the prompt chain for every row of one shard; return per-episode verdicts."""
    assert _TASK_TEXT is not None and _DATASET_DIR is not None
    rel_path = shard.relative_path
    path = _DATASET_DIR / rel_path
    revision_before = _file_revision(path)
    table = read_droid_prompt_population_shard(_DATASET_DIR, shard)
    shard_digest = digest_droid_prompt_shard(table)
    revision_after = _file_revision(path)
    if revision_after != revision_before:
        raise RuntimeError(f"{path} changed while its prompt inputs were being scanned")
    df = table.to_pandas()
    n = len(df)
    task_idx = df["task_index"].to_numpy()

    # tasks.parquet lookup, deduped over the shard's distinct task_index values.
    cleaned_by_task = {int(t): _clean_text(_TASK_TEXT.get(int(t))) for t in np.unique(task_idx)}
    missing = sorted(t for t in cleaned_by_task if t not in _TASK_TEXT)
    resolved = np.array([cleaned_by_task[int(t)] for t in task_idx], dtype=object)

    # Fallback chain, in the reader's order. factorize + per-unique _clean_text
    # keeps this cheap on 100k-row shards of highly repetitive annotation text.
    for col in FALLBACK_COLS:
        todo = resolved == ""
        if not todo.any():
            break
        codes, uniques = pd.factorize(df[col], use_na_sentinel=False)
        cleaned = np.array([_clean_text(u) for u in uniques], dtype=object)[codes]
        hit = todo & (cleaned != "")
        resolved[hit] = cleaned[hit]

    unresolved = pd.Series(resolved == "")
    by_ep = unresolved.groupby(df["episode_index"].to_numpy())
    all_bad = by_ep.all()
    any_bad = by_ep.any()
    return {
        "rel_path": rel_path,
        "source_revision": revision_after,
        "prompt_inputs_shard_digest": shard_digest,
        "rows": n,
        "unresolved_rows": int(unresolved.sum()),
        "episodes_all_unresolved": [int(i) for i in all_bad[all_bad].index.tolist()],
        # A mixed episode would mean the all-or-nothing assumption broke; surfaced
        # rather than silently ignored, because the exclusion list would then be
        # the wrong remedy (some windows are fine, some are not).
        "episodes_partially_unresolved": [int(i) for i in any_bad[any_bad & ~all_bad].index.tolist()],
        "task_index_missing_from_tasks_parquet": missing,
    }


def _file_revision(path: Path) -> tuple[int, int, int]:
    stat = path.stat()
    return stat.st_size, stat.st_mtime_ns, stat.st_ctime_ns


def _parse_episode_indices(value, field: str) -> set[int]:
    if not isinstance(value, list) or any(type(i) is not int or i < 0 for i in value):
        raise ValueError(f"{field} must be a list of non-negative integers")
    return set(value)


def _is_original_generator_artifact(previous: dict, existing: set[int]) -> bool:
    """Recognize the exact top-level artifact emitted by commit a2fa9ea5."""
    if set(previous) != {"reason", "generated", "episode_indices", "stats"}:
        return False
    if previous["reason"] != PROMPT_REASON or not isinstance(previous["generated"], str):
        return False
    if previous["episode_indices"] != sorted(existing):
        return False
    stats = previous["stats"]
    if not isinstance(stats, dict) or set(stats) != {
        "rows_scanned",
        "unresolved_rows",
        "episodes_all_unresolved",
        "episodes_partially_unresolved",
        "fallback_chain",
    }:
        return False
    int_fields = (
        "rows_scanned",
        "unresolved_rows",
        "episodes_all_unresolved",
        "episodes_partially_unresolved",
    )
    if any(type(stats[field]) is not int or stats[field] < 0 for field in int_fields):
        return False
    return (
        stats["rows_scanned"] > 0
        and stats["unresolved_rows"] <= stats["rows_scanned"]
        and stats["episodes_all_unresolved"] == len(existing)
        and stats["episodes_partially_unresolved"] == 0
        and stats["fallback_chain"] == FALLBACK_COLS
    )


def _load_existing_ownership(out: Path) -> tuple[dict, dict, set[int]]:
    """Read and validate the current ownership ledger."""
    if not out.exists():
        return {}, {}, set()
    try:
        snapshot = out.read_bytes()
        previous = json.loads(snapshot)
        if not isinstance(previous, dict):
            raise ValueError("top-level value must be an object")
        existing = _parse_episode_indices(previous["episode_indices"], "episode_indices")
        if DROID_PROMPT_EXCLUSION_KEY in previous:
            previous_prompt = previous[DROID_PROMPT_EXCLUSION_KEY]
            if not isinstance(previous_prompt, dict):
                raise ValueError(f"{DROID_PROMPT_EXCLUSION_KEY} must be an object")
            prompt_owned = _parse_episode_indices(
                previous_prompt["episode_indices"],
                f"{DROID_PROMPT_EXCLUSION_KEY}.episode_indices",
            )
            try:
                independently_owned = _parse_episode_indices(
                    previous_prompt[DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY],
                    f"{DROID_PROMPT_EXCLUSION_KEY}.{DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY}",
                )
            except KeyError as exc:
                raise ValueError(
                    f"{DROID_PROMPT_EXCLUSION_KEY} has no independent ownership ledger; refusing an unsafe rescan"
                ) from exc
            if existing != prompt_owned | independently_owned:
                raise ValueError(
                    "episode_indices must equal the union of prompt-owned and independently-owned exclusions"
                )
            return previous, previous_prompt, independently_owned
        if _is_original_generator_artifact(previous, existing):
            # The original writer overwrote the whole file and its exact schema
            # identifies every canonical ID as prompt-owned. Drop those obsolete
            # top-level fields while migrating to the namespaced ownership ledger.
            return {}, {}, set()
        # With no prompt provenance, every existing canonical exclusion predates
        # this generator and is conservatively treated as independently owned.
        return previous, {}, existing
    except (KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"existing exclusion file {out} is malformed ({exc}); refusing to replace it") from exc


def _validate_total_frames(root: Path, rows_scanned: int) -> None:
    """Keep generator success aligned with the reader's row-count contract."""
    info_path = root / "meta" / "info.json"
    if not info_path.exists():
        return
    try:
        info = json.loads(info_path.read_text())
        if not isinstance(info, dict):
            raise ValueError("top-level value must be an object")
        if "total_frames" not in info:
            return
        expected = info["total_frames"]
        if type(expected) is not int or expected < 0:
            raise ValueError("total_frames must be a non-negative integer")
    except (TypeError, ValueError) as exc:
        raise SystemExit(f"{info_path} is malformed ({exc}); refusing to publish exclusions") from exc
    if rows_scanned != expected:
        raise SystemExit(
            f"prompt scan covered {rows_scanned} rows but {info_path} declares total_frames={expected}; "
            "refusing to publish exclusions"
        )


def _validate_source_snapshot(root, population, tasks_path, tasks_sha256, results, rows) -> None:
    """Recheck every scan input immediately before publishing."""
    _validate_total_frames(root, rows)
    current_population = resolve_lerobot_v3_data_population(root)
    if current_population != population:
        raise SystemExit("info.json or the episodes manifest changed during the prompt scan; refusing to publish")
    if _sha256_file(tasks_path) != tasks_sha256:
        raise SystemExit(f"{tasks_path} changed during the prompt scan; refusing to publish exclusions")
    for result in results:
        path = root / result["rel_path"]
        if _file_revision(path) != tuple(result["source_revision"]):
            raise SystemExit(f"{path} changed during the prompt scan; refusing to publish exclusions")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset-dir", required=True, help="DROID LeRobot v3 bucket root")
    ap.add_argument("--workers", type=int, default=min(32, (os.cpu_count() or 8)))
    ap.add_argument("--dry-run", action="store_true", help="Print the verdict, write nothing")
    args = ap.parse_args()

    root = Path(args.dataset_dir)
    out = root / "meta" / "excluded_episodes.json"
    _load_existing_ownership(out)
    population = resolve_lerobot_v3_data_population(root)
    shards = population.shards
    tasks_path = root / "meta" / "tasks.parquet"
    tasks_bytes = tasks_path.read_bytes()
    tasks_sha256 = hashlib.sha256(tasks_bytes).hexdigest()
    tasks = pd.read_parquet(io.BytesIO(tasks_bytes))
    task_text = dict(zip(tasks["task_index"].to_numpy().tolist(), tasks.index.to_numpy().tolist()))
    logger.info("scanning %d shards under %s with %d workers", len(shards), root, args.workers)

    results = []
    with ProcessPoolExecutor(max_workers=args.workers, initializer=_init, initargs=(str(root), task_text)) as ex:
        futs = [ex.submit(_scan_shard, shard) for shard in shards]
        for i, f in enumerate(as_completed(futs), 1):
            results.append(f.result())
            if i % 50 == 0 or i == len(shards):
                logger.info("  %d/%d shards", i, len(shards))

    bad = sorted({e for r in results for e in r["episodes_all_unresolved"]})
    partial = sorted({e for r in results for e in r["episodes_partially_unresolved"]})
    missing = sorted({t for r in results for t in r["task_index_missing_from_tasks_parquet"]})
    rows = sum(r["rows"] for r in results)
    bad_rows = sum(r["unresolved_rows"] for r in results)

    logger.info("rows scanned: %d", rows)
    logger.info("unresolved rows: %d (%.3f%%)", bad_rows, bad_rows / max(rows, 1) * 100)
    logger.info("episodes with NO resolvable prompt on any row: %d", len(bad))
    if partial:
        logger.error(
            "%d episodes are only PARTIALLY unresolvable — the all-or-nothing assumption this "
            "exclusion list relies on does not hold for them: %s",
            len(partial),
            partial[:20],
        )
    if missing:
        logger.error("task_index values absent from tasks.parquet: %s", missing[:20])
    if partial or missing:
        raise SystemExit(
            "prompt scan violated reader invariants; refusing to publish an exclusion file "
            f"(partially unresolved episodes={len(partial)}, missing task_index values={len(missing)})"
        )
    shard_digests = {}
    for result in results:
        rel_path = result["rel_path"]
        if rel_path in shard_digests:
            raise SystemExit(f"prompt scan returned duplicate shard result for {rel_path}")
        shard_digests[rel_path] = result["prompt_inputs_shard_digest"]
    prompt_inputs_digest = compute_droid_prompt_inputs_digest(
        root,
        shard_digests=shard_digests,
        tasks_sha256=tasks_sha256,
        population=population,
    )

    stats = {
        "rows_scanned": rows,
        "unresolved_rows": bad_rows,
        "episodes_all_unresolved": len(bad),
        "episodes_partially_unresolved": len(partial),
        "task_index_missing_from_tasks_parquet": len(missing),
        "fallback_chain": FALLBACK_COLS,
    }
    with locked_exclusion_files([out]):
        _validate_source_snapshot(root, population, tasks_path, tasks_sha256, results, rows)
        previous, previous_prompt, independently_owned = _load_existing_ownership(out)
        merged = sorted(independently_owned | set(bad))
        prompt_payload = {
            **previous_prompt,
            "reason": PROMPT_REASON,
            "schema_version": DROID_PROMPT_EXCLUSION_SCHEMA_VERSION,
            "fallback_chain": FALLBACK_COLS,
            "episode_indices": bad,
            DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY: sorted(independently_owned),
            "latest_scan": {
                "generated": date.today().isoformat(),
                "episode_indices": bad,
                "stats": stats,
                DROID_PROMPT_INPUTS_DIGEST_KEY: prompt_inputs_digest,
            },
        }
        payload = {
            **previous,
            "episode_indices": merged,
            DROID_PROMPT_EXCLUSION_KEY: prompt_payload,
        }
        if args.dry_run:
            logger.info(
                "--dry-run: would merge %d prompt exclusions into %s (%d total episode_indices)",
                len(bad),
                out,
                len(merged),
            )
            return
        atomic_publish_text(out, json.dumps(payload, indent=2) + "\n")
    logger.info(
        "wrote %s (%d prompt exclusions, %d existing exclusions preserved, %d total)",
        out,
        len(bad),
        len(independently_owned),
        len(merged),
    )


if __name__ == "__main__":
    main()
